package com.testproject.spring_boot_test_project.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * This is a JPA entity that will represent a single todo item.
 * Each todo is owned by only one User. This helps enforce data isolation.
 * The owner relationship is lazy-loaded to avoid unnecessary database queries. This
 * means it only loads the owner information when asked.
 */
@Entity
@Data // Generates getters, setters, toString, equals, hashCode. This automatically generates the needed boilerplate code.
@NoArgsConstructor
@AllArgsConstructor
public class Todo {

    /**
     * Primary key, auto-generated by the database.
     * Marked READ_ONLY so clients cannot set it during creation/update.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private long id = 0; // Is overwritten by @GeneratedValue. Avoids a null check.

    /**
     * The title of the todo.
     * @NotBlank ensures the field is never null, empty, or whitespace-only.
     * Validation happens on create/update via @Valid in the controller.
     */
    @NotBlank(message = "Title Cannot be Empty.")
    private String title;

    /**
     * Completion status of the todo.
     * Defaults to false (new todos are incomplete).
     */
    private boolean completed = false;

    /**
     * The user who owns this todo, this enforces data isolation. Only users who own the todo may interact with it.
     * ManyToOne, a user may have many todos, but a todo may only have one user.
     * FetchType.LAZY: owner is only loaded when accessed vs. always being loaded immediately. Owner data is not always
     * needed.
     * nullable = false, every todo must have an owner.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;
}
