### Get all (should be empty or show previous)
GET http://localhost:8080/api/todos

### Create a Post
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "Organize the house",
  "completed": false
}

### Create an empty title Post
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "",
  "completed": false
}

### Create a Post
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "Go to the gym",
  "completed": false
}

### Create a Post
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "Delete me",
  "completed": false
}

### Delete a todo hardcoded 1
DELETE http://localhost:8080/api/todos/2

### Update a todo hardcoded 3
PUT http://localhost:8080/api/todos/3
Content-Type: application/json

{
  "title": "Updated title – completed now",
  "completed": true
}

### Register a new user (Must Be done first)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "123456"
}

### Log the new user in (Only AFTER Register)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "123456"
}

### Get all again (should now show the new one with id)
GET http://localhost:8080/api/todos

### Get by ID
GET http://localhost:8080/api/todos/1